# Generated by Django 5.0 on 2024-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
