# Generated by Django 5.0 on 2024-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0002_login_deleted_at_login_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
