# Generated by Django 3.2.25 on 2024-10-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0003_tbl_blog_sub_created_at_tbl_blog_sub_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog_sub',
            name='blog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_blogs', to='deerhomesapp.tbl_blogs'),
        ),
    ]
