# Generated by Django 5.0 on 2024-10-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0013_blogs_image_projectss_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
