# Generated by Django 5.0 on 2024-10-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0014_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages'),
        ),
        migrations.AlterField(
            model_name='projectss',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projectimages'),
        ),
    ]
