# Generated by Django 5.0 on 2024-10-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0016_tbl_blog_sub_tbl_blogs_delete_blogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog_sub',
            name='blog_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deerhomesapp.tbl_blogs'),
            preserve_default=False,
        ),
    ]
