# Generated by Django 5.0 on 2024-10-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0017_tbl_blog_sub_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog_sub',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
