# Generated by Django 5.0 on 2024-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0018_tbl_blog_sub_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blog_sub',
            name='sub_title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_blog_sub',
            name='sub_title_content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
