# Generated by Django 5.0 on 2024-09-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0004_projectss_delete_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectss',
            old_name='price',
            new_name='amount',
        ),
    ]
