# Generated by Django 5.0 on 2024-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0005_rename_price_projectss_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectss',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
