# Generated by Django 5.0 on 2024-09-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deerhomesapp', '0010_contactus_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
